apiVersion: v1
kind: ReplicationController
metadata:
  name: alpine-sshd
spec:
   replicas: 1
   selector:
     os: alpine
   template:
     metadata:
       labels:
         os: alpine
     spec:
       containers:
       - name: alpine-sshd
         image: panubo/sshd:latest
         ports:
         - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-sshd
spec:
  type: NodePort
  ports:
   - port: 22
     nodePort: 30022
     targetPort: 22
  selector:
    os: alpine
