version: '2'

services:
  # jenkins service based on Jenkins LTS version
  jenkins:
          image: jenkins-master:latest
    ports:
      - "32002:8080"
      - "50000:50000"
    environment:
      - JENKINS_ADMIN_ID=root
      - JENKINS_ADMIN_PW=jenkins
      - JENKINS_MODE=master
    volumes:
      - ./data/:/data/jenkins
    restart: "no"
