apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jenkins-slave
  namespace: jenkins
  labels:
    k8s-app: jenkins-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jenkins-slave
  template:
    metadata:
      labels:
        k8s-app: jenkins-slave
    spec:
      containers:
      - name: jenkins-slave
        image: jenkins-slave:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: JENKINS_MODE 
            value: "slave"
          - name: JENKINS_MASTER_URL
            value: "http://192.168.8.100:30080/computer/node1/slave-agent.jnlp"
          - name: JENKINS_SLAVE_SECRET
            value: "2db7334e5d74ac24d008559346d4a6b5e3c346990b71dcde5ad37825496f093d"
          - name: JENKINS_SLAVE_WORKDIR
            value: "/tmp/jenkins"
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: "1"
            memory: 512Mi
